# Default application configuration that all configurations inherit from.

exclude:
- './vendor/**'
- './bower_components/**'


linters:
  BorderZero: # Prefer border: 0 over border: none.
    enabled: true
    severity: warning

  CapitalizationInSelector: # IDs, classes, types, placeholders, and pseudo-selectors should be all lowercase.
    enabled: true
    severity: warning

  ColorKeyword: # Prefer hexadecimal color codes over color keywords.
    enabled: true
    severity: error

  Comment: # // comments should be preferred as they don't get rendered in the final generated CSS, whereas /* ... */ comments do.
    enabled: false
    severity: error

  DebugStatement: # Reports @debug statements (which you probably left behind accidentally).
    enabled: true
    severity: warning

  DeclarationOrder: # Write @extend statements first in rule sets, followed by property declarations and then other nested rule sets.
    enabled: true
    severity: error

  DuplicateProperty: # Reports when you define the same property twice in a single rule set.
    enabled: true
    severity: warning

  EmptyLineBetweenBlocks: # Separate rule, function, and mixin declarations with empty lines.
    enabled: true
    severity: warning
    ignore_single_line_blocks: true

  EmptyRule: # Reports when you have an empty rule set.
    enabled: true
    severity: warning

  FinalNewline: # Files should always have a final newline.
    enabled: true
    severity: error
    present: true

  HexLength: # You can specify whether you prefer shorthand or long-form hexadecimal colors by setting the style option to short or long, respectively.
    enabled: false
    severity: warning
    style: short # or 'long'

  HexNotation: # Checks if hexadecimal colors are written in lowercase. You can specify which case with the style option.
    enabled: true
    severity: warning
    style: lowercase # or 'uppercase'

  HexValidation: # Ensure hexadecimal colors are valid (either three or six digits).
    enabled: true
    severity: error

  IdWithExtraneousSelector: # Don't combine additional selectors with an ID selector.
    enabled: true
    severity: error

  Indentation: # Use two spaces per indentation level. No hard tabs.
    enabled: true
    severity: error
    width: 2

  LeadingZero: # Don't write leading zeros for numeric values with a decimal point.
    enabled: false
    severity: warning
    style: exclude_zero # or 'include_zero'

  MergeableSelector: # Reports when you define the same selector twice in a single sheet.
    enabled: true
    severity: warning
    force_nesting: true

  NameFormat: # Functions, mixins, and variables should be declared with all lowercase letters and hyphens instead of underscores.
    enabled: true
    severity: warning
    convention: hyphenated_lowercase # or 'BEM', or a regex pattern

  NestingDepth: # Avoid nesting selectors too deeply.
    enabled: true
    severity: warning
    max_depth: 5

  PlaceholderInExtend: # Always use placeholder selectors in @extend
    enabled: false
    severity: warning

  PropertySortOrder: # ort properties in a strict order. By default, will require properties be sorted in alphabetical order
    enabled: true
    severity: warning

  PropertySpelling: # Reports when you use an unknown CSS property (ignoring vendor-prefixed properties).
    enabled: true
    severity: warning
    extra_properties: []

  SelectorDepth: # Don't write selectors with a depth of applicability greater than x.
    enabled: true
    severity: warning
    max_depth: 5

  Shorthand: # Prefer the shortest shorthand form possible for properties that support it.
    enabled: false
    severity: warning

  SingleLinePerSelector: # Split selectors onto separate lines after each comma.
    enabled: true
    severity: error

  SpaceAfterComma: # Commas in lists should be followed by a space.
    enabled: false
    severity: warning

  SpaceAfterPropertyColon: # Properties should be formatted with a single space separating the colon from the property's value.
    enabled: true
    severity: warning

  SpaceAfterPropertyName: # Properties should be formatted with no space between the name and the colon.
    enabled: true
    severity: error

  SpaceBeforeBrace: # Opening braces should be preceded by a single space.
    enabled: true
    severity: warning
    allow_single_line_padding: false

  SpaceBetweenParens: # Parentheses should not be padded with spaces.
    enabled: true
    severity: error
    spaces: 0

  StringQuotes: # String literals should be written with single quotes unless using double quotes would save on escape characters.
    enabled: true
    severity: warning
    style: single_quotes # or double_quotes

  TrailingSemicolonAfterPropertyValue: # Property values should always end with a semicolon.
    enabled: true
    severity: error

  UnnecessaryMantissa: # Numeric values should not contain unnecessary fractional portions.
    enabled: true
    severity: warning

  UrlFormat: # URLs should not contain protocols or domain names.
    enabled: true
    severity: warning

  UrlQuotes: # URLs should always be enclosed within quotes.
    enabled: true
    severity: error

  ZeroUnit: # Omit length units on zero values.
    enabled: true
    severity: warning

  Compass::*:
    enabled: false
